### ISSUE TITLE
enable_gpu doesn't seem to work

### ISSUE THREAD

**Issue by jack-digilabs** [RoverRobotics/rr_mxnet#1]
When I run a node with the parameters listed below and then tell it to start running using *rostopic pub /rr_mxnet_ssd/enable std_msgs/Bool True -1'* , the node runs and I get detections however looks at the cpu/gpu stats using *sudo ~/tegrastats* I see no GPU usage and 100% for all CPUs. I did a little digging and found mx's built in test *mx.test_utils.list_gpus()* on TX1's I get nothing returned however if I use it on Anton, I get 1 gpu returned. So I refered [here](https://github.com/awslabs/mxnet-lambda/blob/master/src/mxnet/test_utils.py) to find what *list_gpus()* does which seems to just look at a few directories and as far as I can tell, those directories don't exist on the TX1's. So I'm presuming this means mxnet isn't using the GPU because it doesn't see it?

Below are the params I'm using.

```
<!-- MxNet SSD (Detector) -->
    <node name="rr_mxnet_ssd" pkg="rr_mxnet" type="mxnet_ssd_node.py" output="screen" >
      <param name="image_topic" value="/usb_cam_front/image" />
      <param name="mask_topic" value="/rr_mxnet_segmentation/segmentation_mask" />
      <param name="detections_topic" value="~detections" />
      <param name="publish_detection_images" value="true" type="bool" />
      <param name="image_detections_topic" value="~image" />
      <param name="throttle_timer" value="5" type="int" />
      <param name="threshold" value="0.35" type="double" />
      <param name="latency_threshold" value="1" type="int" />
      <param name="start_enabled" value="false" type="bool" />
      <param name="start_zoom_enabled" value="false" type="bool" />
      <param name="level0_ncrops" value="2" type="int" />
      <param name="level1_xcrops" value="4" type="int" />
      <param name="level1_ycrops" value="2" type="int" />
      <param name="level1_crop_size" value="380" type="int" />
      <param name="model_directory" value="/home/ubuntu/mxnet_ssd/" />
      <param name="classes" value="goose, person, golfcart, lawncare, dog" />
      <param name="enable_gpu" value="false" type="bool" />
      <param name="batch_size" value="2" type="int" />
      <param name="model_filename" value="goosenet_v0_2_1.params" />
      <param name="network" value="custom-ssd_512_resnet50_v1_custom" />
      <param name="save_detections" value="false" type="bool" />
      <param name="save_directory" value="/tmp" />
    </node>
```

**Comment by erikbeall** [comment]
Pretty silly bug, wasn't copying the data over to the GPU context. Fixed in commit 3db2656a19d4d8617bf1f5721eff8854fd71021d. Note, in the Tegra platform, GPU and CPU RAM are shared, and the MxNet backend (and probably all backends written for machine learning with PCIe graphics cards with separate GPU memory) is not written to sensibly share the same memory and instead duplicates the memory usage. There is no workaround as yet, just be aware of the memory usage on Tegra and other NVidia systems like it- will add to wiki.
