### ISSUE TITLE
Latency threshold doesn't seem to work

### ISSUE THREAD

**Issue by jack-digilabs** [RoverRobotics/rr_mxnet#3]
I have the latency threshold set to 1 but I'm receiving detections that have a detections time stamp minus image_source time stamp greater than the latency threshold. Am I misinterpreting what the latency threshold is or is this a bug?

**Comment by erikbeall** [comment]
I think I'd call it a "Documentation bug". The latency threshold (will update the wiki) is used by the mxnet_node to compare image timestamps with rospy.now(), or how old is the image I just got in the callback. If the image is older than latency, the callback just returns, essentially skipping the image. There is a lower bound on latency, so if you set latency to zero, it'll think all images are too old and this node will basically be blind.

Assuming the image isn't skipped, then the inference adds further time, so when you get a detection, the difference between the source_img.header.stamp and the detection.header.stamp may be larger than this diffference. FYI, on my laptop (Intel, GTX1050) I can set latency to 0.2 safely. Each platform will have different latencies in how the image gets to this node.
